### ISSUE TITLE
ReferenceError: Cypress is not defined

### ISSUE THREAD

**Issue by nde-agridea** [prma85/cypress-azure-keyvault#2]
I cannot get the plugin to work as explained in the readme, when referencing it in plugins/index.js, the test runner fails with the error message below. The offending line is in dist/support/index.js: 

`Cypress.Commands.add("getKeyvaultData", azure_1.getKeyvaultData);`

```
ReferenceError: Cypress is not defined    at Object.<anonymous> (C:\Users\nde\source\repos\cypress-test\node_modules\cypress-azure-keyvault\dist\support\index.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12789)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\nde\source\repos\cypress-test\node_modules\cypress-azure-keyvault\dist\index.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12789)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
```

**Comment by robhalevt** [comment]
I'm encountering a similar error following the readme. I have an existing simple test which passes. As I follow the instructions on the readme, and run the test after each step, I see:

1. Run the `npm install cypress-azure-keyvault --save-dev` command ✔️ 
2. Edit the `cypress\support\index.js` file to have `import 'cypress-azure-keyvault';` ✔️ 
3. Edit the `cypress\plugins\index.js` to have `const { azureKeyvaultPlugin } = require("cypress-azure-keyvault");` ❌ 

The test fails to run with the following.

```
The plugins file is missing or invalid.

Your `pluginsFile` is set to `C:\Research\Sample.Cypress.Automation\cypress\plugins\index.js`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js`, `.ts`, or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile`. If that's the case, restart the test runner.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.

 ReferenceError: Cypress is not defined
    at Object.<anonymous> (C:\Research\Sample.Cypress.Automation\node_modules\cypress-azure-keyvault\src\support\index.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Research\Sample.Cypress.Automation\node_modules\cypress-azure-keyvault\src\index.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Research\Sample.Cypress.Automation\cypress\plugins\index.js:17:33)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
```

**Comment by its-vincesanity** [comment]
It seems the plugin path is just wrong in the readme.md....

I adjusted it:
**Javascript**
```
const { azureKeyvaultPlugin } = require("cypress-azure-keyvault/dist/plugins");
module.exports = (on, config) => {
  return azureKeyvaultPlugin(on, config);
};
```
**Typescript**
```
import { azureKeyvaultPlugin } from  "cypress-azure-keyvault/dist/plugins";
export default (on, config) => azureKeyvaultPlugin(on, config);
```
